# base stage:
# Install dependencies for deployment to get minimum size for deployer.
# For deployment environment, only occlum-runtime and sgx-psw are needed.
FROM ubuntu:20.04 as base
LABEL maintainer="Chunyang Hui <sanqian.hcy@antgroup.com>"

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends gnupg wget ca-certificates jq && \
    echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main' | tee /etc/apt/sources.list.d/intel-sgx.list && \
    wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | apt-key add - && \
    echo 'deb [arch=amd64] https://occlum.io/occlum-package-repos/debian focal main' | tee /etc/apt/sources.list.d/occlum.list && \
    wget -qO - https://occlum.io/occlum-package-repos/debian/public.key | apt-key add - && \
    apt-get update && \
    apt-get install -y  occlum=0.29.7-1 occlum-sgx-tools=0.29.7-1 occlum-pal=0.29.7-1 occlum-runtime=0.29.7-1 libsgx-uae-service libsgx-dcap-ql libsgx-dcap-ql-dev libsgx-quote-ex-dev &&\
    apt-get install -y libsgx-urts libsgx-dcap-default-qpl
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENV PATH="/opt/occlum/build/bin:/usr/local/occlum/bin:$PATH"
RUN apt update && apt install m4 make -y

# packager stage:
# Users can build their own applications and put to occlum instance.
# And then use "occlum package" to get a minimum subset of files to run in deployment environment.
# In this demo, the occlum instance is built in debug mode.
# So "--debug" flag is required for the "occlum package".
FROM occlum/occlum:0.29.7-ubuntu20.04 as packager
WORKDIR /RUST
RUN rustup install nightly-2023-06-05-x86_64-unknown-linux-gnu && \
    rustup default nightly-2023-06-05-x86_64-unknown-linux-gnu && \
    rustup target add x86_64-unknown-linux-musl
COPY ./ ./
WORKDIR /RUST
RUN chmod +x ./run_rust_demo_on_occlum_docker.sh && \
    ./run_rust_demo_on_occlum_docker.sh && \
    cd occlum_instance &&\
    occlum package --debug

# deployer stage:
# Unpack the package from packager
FROM base as deployer
WORKDIR /root
COPY --from=packager /RUST/occlum_instance/occlum_instance.tar.gz .
RUN tar -xvzf occlum_instance.tar.gz
COPY --from=packager /etc/sgx_default_qcnl.conf /etc
RUN    mkdir -p /var/run/aesmd && \
    echo "LD_LIBRARY_PATH=/opt/intel/sgx-aesm-service/aesm nohup /opt/intel/sgx-aesm-service/aesm/aesm_service --no-daemon >/dev/null 2>&1 &" > /root/.bashrc

WORKDIR /root
